services:
  - type: web
    name: ameja
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: AMEJA_PUBLIC_BASE_URL
        sync: false
      - key: AMEJA_PAGES_DIR
        value: ./test_site/pages
